services:
  server:
    platform: linux/amd64
    container_name: "rust-dc-bot-dev"
    build:
      context: .
      dockerfile: "./Dockerfile.dev"
    env_file:
      - .env.local.dev
    # ports:
    #   - 8081:8081 
    volumes:
      - ./:/app
